### ISSUE TITLE
Promotion conditions for excluding catalog

### ISSUE THREAD

**Issue by bear133** [VirtoCommerce/vc-module-marketing#6]
Our customer would like to make store wide promotions but exclude say a brand or a category. Currently the conditions can only be true not false.

**Comment by OlegoO** [comment]
Also want to suggest add condition for excluding products

**Comment by tatarincev** [comment]
I've tried to add to condition `ConditionCategoryIs` the default `excluding` children elements by adding next code
```
 dynamicExpressionService.registerExpression({
          id: 'ConditionCategoryIs',
          displayName: 'Category is []',
          availableChildren: availableExcludings,
          newChildLabel: '+ excluding'
      });
```
and it looked as expected
![image](https://user-images.githubusercontent.com/7566324/30868304-83ca8fc6-a2de-11e7-91cc-e4edcb3f5ab0.png)
But after saved promotion category name was replaced to category identifier
![image](https://user-images.githubusercontent.com/7566324/30868384-c1dc185c-a2de-11e7-82c6-63cf9a24b070.png)

Probably solution:
Need to preload categories in this [promotion-detail.js](https://github.com/VirtoCommerce/vc-module-marketing/blob/master/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js#L164) for display category name.  But I facing some problems that were not available to use the promise operation (to load categories from API) within the initialization of the expression tree code, because [the tree clone operation](https://github.com/VirtoCommerce/vc-module-marketing/blob/master/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js#L37) happens before the operation for categories loading completed.

**Comment by tatarincev** [comment]
@eMazeika  Please look at this issue, I need your help.

**Comment by bear133** [comment]
Looks like this is on the right track. But the purposed solution would not cover my example. As the our customer would like store-wide promotions excluding some categories. I belive this should be on the "top level" _if any of these catalog conditions are **NOT** true_

**Comment by tatarincev** [comment]
Is the logical inversion for the whole block suitable for you?
Some like this
![image](https://user-images.githubusercontent.com/7566324/30903862-7e5463f4-a370-11e7-8a18-10d14c1c2ea2.png)

**Comment by bear133** [comment]
Yeah that solution would be perfect for us!

**Comment by tatarincev** [comment]
Also, need to make Not inversion clauses for next condition expressions "IsCategory", "IsProduct", "CurrencyIs"  etc.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-dynamic-expressions/releases/tag/v2.12.5
